[workspace]
members = ["jf_native_core", "jf_native_abi"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"
authors = ["Jellyfin Contributors"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
